#!/bin/bash

#    Starting chromium with Open CDM enabled.
#
#    Tested with EME test site:
#
#    http://people.linaro.org/~peter.griffin/dash.js/samples/dash-if-reference-player/eme.html


/usr/bin/chromium/chrome --no-sandbox  \
    --use-gl=egl --ozone-platform=wayland --no-sandbox --composite-to-mailbox --in-process-gpu --enable-low-end-device-mode \
    --enable-logging --v=0 \
    --start-maximized \
    --user-data-dir=data_dir \
    --blink-platform-log-channels=Media\
    --register-pepper-plugins="/usr/lib/chromium/libopencdmadapter.so#ClearKey CDM#ClearKey CDM0.1.0.0#0.1.0.0;application/x-ppapi-open-cdm" \
    $@
